name: pickup_game
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
  firebase_core: ^1.4.0
  font_awesome_flutter: ^9.1.0
  auth_repository:
    path: packages/auth_repository
  profile_repository:
    path: packages/profile_repository
  field_repository:
    path: packages/field_repository
  game_repository:
    path: packages/game_repository
  pickup_game_ui:
    path: packages/pickup_game_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  firebase_auth_mocks: ^0.8.0
  google_sign_in_mocks: ^0.2.1
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
