name: profile_repository
description: Profile repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true
