name: pickup_game_ui
description: Pickup Game UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
